# PRUEBA CON DATOS online_retail

- Hace falta crear columna total que represente el precio total del pedido
- Dropear Nulos

In [ ]:
from segmentaciones.LRFM_DEFI.input_management import DatasetMapper
import pandas as pd
data = pd.read_excel('../../data/online+retail/Online_retail.xlsx')
data = data.dropna()
data.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [16]:
data['total'] = data['Quantity']*data['UnitPrice']

In [18]:
mapper = DatasetMapper()
data_clean = mapper.transform(data)

Mapeo automático:
  id_usuario <- CustomerID (confianza: 1.00)
  total_pedido <- total (confianza: 1.00)
  fecha_pedido <- InvoiceDate (confianza: 0.90)
  id_pedido <- InvoiceNo (confianza: 0.65)

In [20]:
data_clean.dtypes

id_usuario              object
total_pedido           float64
fecha_pedido    datetime64[ns]
id_pedido               object
dtype: object

# PRUEBA CON THELOOK

In [21]:
import pandas as pd
data = pd.read_csv("../../data/thelook/procesado/orders_price_client.csv")
data.head(5)

   order_id  user_id           created_at  sale_price  product_id
0     10826     8614  2020-06-28 00:40:17         2.5       13606
1     13243    10505  2022-03-01 05:18:44         2.5       13606
2     53140    42340  2021-04-11 01:31:52         2.5       13606
3    104681    83704  2022-03-29 21:37:06         2.5       13606
4    117931    94363  2021-02-17 09:28:17         2.5       13606

In [22]:
mapper = DatasetMapper()
data_clean = mapper.transform(data)

Mapeo automático:
  id_usuario <- user_id (confianza: 1.00)
  id_pedido <- order_id (confianza: 1.00)
  fecha_pedido <- created_at (confianza: 1.00)
  total_pedido <- sale_price (confianza: 0.82)